server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}

spring:
  application:
    name: GATEWAY

logging:
  file:
    name: LOG_GATEWAY.TXT

