server:
  port: 8083
  forward-headers-strategy: framework
eureka:
#  baseServerUrl: 192.168.100.10
  baseServerUrl: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.baseServerUrl}:8080/eureka}

spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: authentication
          predicates:
            - Path=/authentication/**
          uri: lb://AUTHENTICATION
        - id: transport
          predicates:
            - Path=/transport/**
          uri: lb://TRANSPORT
        - id: basicData
          predicates:
            - Path=/basicData/**
          uri: lb://BASICDATA
        - id: login
          predicates:
            - Path=/login
          uri: lb://AUTHENTICATION
        - id: logout
          predicates:
            - Path=/logout
          uri: lb://AUTHENTICATION
        - id: transportSwagger
          uri: lb://TRANSPORT
          predicates:
            - Path=/transportSwagger/**
          filters:
            - RewritePath=/transportSwagger/(?<segment>.*), /${segment}
            - SetRequestHeader=Authorization, $httpHeader(Authorization)
        - id: basicDataSwagger
          uri: lb://BASICDATA
          predicates:
            - Path=/basicDataSwagger/**
          filters:
            - RewritePath=/basicDataSwagger/(?<segment>.*), /${segment}
            - SetRequestHeader=Authorization, $httpHeader(Authorization)
        - id: authenticationSwagger
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/authenticationSwagger/**
          filters:
            - RewritePath=/authenticationSwagger/(?<segment>.*), /${segment}
            - SetRequestHeader=Authorization, $httpHeader(Authorization)

logging:
  file:
    name: LOG_GATEWAY.TXT
#  level:
#    org.springframework.cloud.gateway: DEBUG

redis:
  port: 6379
  size: 512mb
  limit: 3
  time-interval-in-seconds: 60
  excluded-endpoints: /authenticationSwagger/,/transportSwagger/,/basicDataSwagger/